package com.kie_pract.hcm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Fruit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String name;

	private java.lang.String selected_date;

	private Float total_count_late_early;

	private Float total_Frequent_leave;

	private Float total_well_leave;

	private Float total_lwp_leave;

	private Float total_lwa_leave;

	private java.lang.String date;

	private java.lang.Integer total_employees;

	private Float filled_employees;

	private Float not_filled_count;

	private Float count_of_Employees_with_TTE_Task;

	private java.lang.Float ttePer;

	private java.lang.Integer sum;

	public Fruit() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSelected_date() {
		return this.selected_date;
	}

	public void setSelected_date(java.lang.String selected_date) {
		this.selected_date = selected_date;
	}

	public java.lang.String getDate() {
		return this.date;
	}

	public void setDate(java.lang.String date) {
		this.date = date;
	}

	public java.lang.Integer getTotal_employees() {
		return this.total_employees;
	}

	public void setTotal_employees(java.lang.Integer total_employees) {
		this.total_employees = total_employees;
	}

	public java.lang.Float getTtePer() {
		return this.ttePer;
	}

	public void setTtePer(java.lang.Float ttePer) {
		this.ttePer = ttePer;
	}

	public java.lang.Integer getSum() {
		return this.sum;
	}

	public void setSum(java.lang.Integer sum) {
		this.sum = sum;
	}

	public java.lang.Float getTotal_count_late_early() {
		return this.total_count_late_early;
	}

	public void setTotal_count_late_early(java.lang.Float total_count_late_early) {
		this.total_count_late_early = total_count_late_early;
	}

	public java.lang.Float getTotal_Frequent_leave() {
		return this.total_Frequent_leave;
	}

	public void setTotal_Frequent_leave(java.lang.Float total_Frequent_leave) {
		this.total_Frequent_leave = total_Frequent_leave;
	}

	public java.lang.Float getTotal_well_leave() {
		return this.total_well_leave;
	}

	public void setTotal_well_leave(java.lang.Float total_well_leave) {
		this.total_well_leave = total_well_leave;
	}

	public java.lang.Float getTotal_lwp_leave() {
		return this.total_lwp_leave;
	}

	public void setTotal_lwp_leave(java.lang.Float total_lwp_leave) {
		this.total_lwp_leave = total_lwp_leave;
	}

	public java.lang.Float getTotal_lwa_leave() {
		return this.total_lwa_leave;
	}

	public void setTotal_lwa_leave(java.lang.Float total_lwa_leave) {
		this.total_lwa_leave = total_lwa_leave;
	}

	public java.lang.Float getFilled_employees() {
		return this.filled_employees;
	}

	public void setFilled_employees(java.lang.Float filled_employees) {
		this.filled_employees = filled_employees;
	}

	public java.lang.Float getNot_filled_count() {
		return this.not_filled_count;
	}

	public void setNot_filled_count(java.lang.Float not_filled_count) {
		this.not_filled_count = not_filled_count;
	}

	public java.lang.Float getCount_of_Employees_with_TTE_Task() {
		return this.count_of_Employees_with_TTE_Task;
	}

	public void setCount_of_Employees_with_TTE_Task(
			java.lang.Float count_of_Employees_with_TTE_Task) {
		this.count_of_Employees_with_TTE_Task = count_of_Employees_with_TTE_Task;
	}

	public Fruit(java.lang.String name, java.lang.String selected_date,
			java.lang.Float total_count_late_early,
			java.lang.Float total_Frequent_leave,
			java.lang.Float total_well_leave, java.lang.Float total_lwp_leave,
			java.lang.Float total_lwa_leave, java.lang.String date,
			java.lang.Integer total_employees,
			java.lang.Float filled_employees, java.lang.Float not_filled_count,
			java.lang.Float count_of_Employees_with_TTE_Task,
			java.lang.Float ttePer, java.lang.Integer sum) {
		this.name = name;
		this.selected_date = selected_date;
		this.total_count_late_early = total_count_late_early;
		this.total_Frequent_leave = total_Frequent_leave;
		this.total_well_leave = total_well_leave;
		this.total_lwp_leave = total_lwp_leave;
		this.total_lwa_leave = total_lwa_leave;
		this.date = date;
		this.total_employees = total_employees;
		this.filled_employees = filled_employees;
		this.not_filled_count = not_filled_count;
		this.count_of_Employees_with_TTE_Task = count_of_Employees_with_TTE_Task;
		this.ttePer = ttePer;
		this.sum = sum;
	}

}